//let promesa = new Promise(function (resolve, reject)){
//    if(false){
//        resolve("la promesa finalizo correctamente");
//    }else{
//        reject("ha ocurrido un error");
//    }
//}

//Con catch capturamos las promesas rechazadas y definimos bloque de codigo para trabajar error
//promesa.catch(function (error)){
//    console.log("respuesta: " + error)
//}